services:
  aura-db:
    image: postgres:17
    container_name: aura-db
    hostname: aura-db
    restart: always
    # command: postgres -c 'max_connections=5000'
    # shm_size: 8gb
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=UTC
    ports:
      - '5432:5432'
    # networks:
    #   - aura-network
    volumes:
      - aura-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 3s
      timeout: 10s
      retries: 3

  aura-redis:
    image: valkey/valkey:8.0.2-alpine
    container_name: aura-redis
    hostname: aura-redis
    restart: always
    ports:
      - '6379:6379'
    # networks:
    #   - aura-network
    volumes:
      - aura-redis-data:/data
    healthcheck:
      test: [ "CMD", "valkey-cli", "ping" ]
      interval: 3s
      timeout: 10s
      retries: 3

volumes:
  aura-db-data:
    driver: local
    external: false
    name: aura-db-data
  aura-redis-data:
    driver: local
    external: false
    name: aura-redis-data

#networks:
#  aura-network:
#    external: true
