name: Build Dev

on:
  workflow_dispatch:
  push:
    branches:
      - dev


jobs:
  send-start-deploy-telegram-message:
    name: 📢 Send Telegram message
    runs-on: ubuntu-latest
    steps:
      - name: 🔧 Checkout source code
        uses: actions/checkout@v4

      - name: 📬 Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🏹 Начало деплоя пакета ${{ github.REPOSITORY }}
            Коммит: ${{ github.event.head_commit.message }}
            Автор: ${{ github.event.head_commit.author.name }}
            Время: ${{ github.event.head_commit.timestamp }}

  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: 🔧 Checkout source code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: 🔧 Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 🔧 Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🔧 Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 📤 Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: DockerfileDev
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            localzet/aura-backend:dev
            ghcr.io/localzet/aura-backend:dev


  send-finish-tg-msg:
    name: 📢 Send Telegram message
    needs: [ build-docker-image ]
    runs-on: ubuntu-latest
    steps:
      - name: 🔧 Checkout source code
        uses: actions/checkout@v4

      - name: 📬 Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ Пакет ${{ github.REPOSITORY }} успешно опубликован
            Тег: *${{ github.sha }}*
            Коммит: ${{ github.event.head_commit.message }}
            Автор: ${{ github.event.head_commit.author.name }}
            Время: ${{ github.event.head_commit.timestamp }}

  notify-on-error:
    runs-on: ubuntu-latest
    needs: [ build-docker-image ]
    if: failure()
    steps:
      - name: 🔧 Checkout source code
        uses: actions/checkout@v4

      - name: 🚨 Send error notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❌ Ошибка в ${{ github.REPOSITORY }}: проблемы в сборке
